#!/bin/bash
# DockerHub build hook: https://docs.docker.com/docker-hub/builds/advanced/

docker build --pull --build-arg BUILD_DATE=`date +%FT%TZ` \
    --build-arg VERSION=`git describe --match "v[0-9]*" --tags HEAD --always` \
    --build-arg BUILD_REVISION=$SOURCE_COMMIT \
    -f $DOCKERFILE_PATH -t $IMAGE_NAME .
