name: Docker Image Build

on:
  push:
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'

# TODO handle releases

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push
    steps:
    - uses: actions/checkout@v2
      with:
        # History of 500 should be more than enough to calculate commit count since last release tag.
        fetch-depth: 500
    - name: Fetch all tags to determine version
      run: |
        git fetch origin +refs/tags/*:refs/tags/*
        git describe --match "v[0-9]*" --tags HEAD --always
    - name: Build, Tag, Push
      run: |
        docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
        docker build --pull \
          --build-arg BUILD_DATE=`date +%FT%TZ` \
          --build-arg VERSION=`git describe --match "v[0-9]*" --tags HEAD --always` \
          --build-arg BUILD_REVISION=$GITHUB_SHA \
          -t docker.pkg.github.com/zehnm/yio-crosscompile-action/yio-crosscompile:latest \
          -f Dockerfile .
        docker push docker.pkg.github.com/zehnm/yio-crosscompile-action/yio-crosscompile:latest

  release:
    name: Create Release
    if: github.ref == 'refs/heads/master' || contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create Pre-Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: "!contains(github.ref, 'tags/v')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: "contains(github.ref, 'tags/v')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
